# 
site_name: shafish.cn
site_url: https://shafish.cn
site_author: shafish
site_description: >-
  Just write something about Work、Technology and Life.

copyright: Copyright &copy; 2018 - 2021 shafish

theme:
  name: material
  custom_dir: overrides
  language: zh
  # 网站图标
  #font:
    #text: Roboto
    #code: Roboto Mono
  #favicon: assets/favicon.png
  # 网站字体
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: 关灯
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 开灯
  features:
    - navigation.instant # without fully reloading the page
    - navigation.tracking
    - navigation.tabs # nav top目录显示在标题栏
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    #- navigation.expand  # 每次刷新都展开子节点
    #- navigation.indexes  # 无效？？
    #- toc.integrate  # 目录展开在字节点下
    - navigation.top # 一键回顶 top
    - search.suggest
    - search.highlight
    #- header.autohide
    - content.code.annotate
    - header.autohide

plugins:
  - search

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<shafish_cn@163.com>
      name: 发送邮件

extra_css:
  - stylesheets/extra.css

#extra_javascript:

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets 
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - pymdownx.details  
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true  

nav:
  - 技术:
    - blog/index.md
    #- 2022:
     # - blog/2022/index.md
      #- 第一篇文章: blog/2022/1.md
    - 2021年:
      #- blog/2021/index.md
      - 12月份: 
        - nginx使用记录: blog/2021/12/nginx_record.md
  - 生活: life/index.md
  - 关于: about.md